import Head from "next/head";
import React from "react";
import styled from "styled-components";
import DemoSection from "../components/DemoSection";
import Footer from "../components/Footer";
import NavBar from "../components/NavBar";
import Image from "next/image";
import { DM_Serif_Display, Public_Sans } from "@next/font/google";
import InformationBlock from "../components/InformationBlock";

const dm = DM_Serif_Display({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400"],
});
const publicSans = Public_Sans({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "700", "800"],
});

const MainArea = styled.main`
  position: relative;
`;

const Spacer = styled.div`
  width: 100%;
  height: 126px;

  @media screen and (min-width: 768px) {
    height: 163px;
  }
`;

const ImageContainer = styled.div`
  position: absolute;
  display: block;
  width: 780px;
  height: 780px;
  left: 74px;
  top: -644px;

  @media screen and (min-width: 768px) {
    left: 505px;
    top: -504px;
  }
  @media screen and (min-width: 1440px) {
    left: 800px;
    top: -527px;
  }
`;

const AboutSection = styled.section`
  width: 100%;
  height: auto;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: flex-start;
  padding: 0 24px;
  margin-bottom: 40px;

  @media screen and (min-width: 768px) {
    margin-bottom: 54px;
  }
`;

const AboutSectionWrapper = styled.section`
  width: 100%;
  max-width: 573px;
  height: auto;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: flex-start;

  @media screen and (min-width: 768px) {
    margin: 0 auto;
  }

  @media screen and (min-width: 1440px) {
    max-width: 920px;
  }
`;

const AboutTitle = styled.h1`
  color: #36536b;
  font-size: 32px;
  font-weight: 400;
  line-height: 36px;
  letter-spacing: -0.2461538463830948px;
  text-align: center;

  @media screen and (min-width: 768px) {
    font-size: 48px;
    font-weight: 400;
    line-height: 56px;
    letter-spacing: -0.3692307770252228px;
    text-align: center;
  }
  @media screen and (min-width: 1440px) {
    font-size: 56px;
    font-weight: 400;
    line-height: 56px;
    letter-spacing: -0.4307692348957062px;
    text-align: left;
  }
`;

const About = () => {
  return (
    <MainArea>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <ImageContainer>
        <Image
          src={"/assets/shared/desktop/bg-pattern-circle.svg"}
          alt={"circle"}
          fill
          priority={true}
          quality={100}
        />
      </ImageContainer>
      <Spacer />
      <AboutSection>
        <AboutSectionWrapper>
          <AboutTitle className={dm.className}>
            We empower innovators by delivering access to the financial system
          </AboutTitle>
        </AboutSectionWrapper>
      </AboutSection>
      <InformationBlock />
      <DemoSection />
      <Footer />
    </MainArea>
  );
};

export default About;
