import Head from "next/head";
import styled from "styled-components";
import Header from "../components/Header";
import NavBar from "../components/NavBar";
import CustomerSection from "../components/CustomerSection";
import FeatureSection from "../components/FeatureSection";
import PropertySection from "../components/PropertySection";
import DemoSection from "../components/DemoSection";
import Footer from "../components/Footer";

const MainArea = styled.main`
  position: relative;
`;

export default function Home() {
  return (
    <MainArea>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Header />
      <CustomerSection />
      <FeatureSection
        reverse={false}
        title={"Easy to implement"}
        description={
          "Our API comes with just a few lines of code. You’ll be up and running in no time. We built our documentation page to integrate payments functionality with ease."
        }
        image={
          "/assets/home/desktop/illustration-easy-to-implement-cropped.svg"
        }
        alt={"eaasy"}
      />
      <FeatureSection
        reverse={true}
        title={"Simple UI & UX"}
        description={
          "Our pre-built form is easy to integrate in your app or website’s checkout flow and designed to optimize conversion. "
        }
        image={"/assets/home/desktop/illustration-simple-ui-cropped.svg"}
        alt={"simple"}
      />
      <PropertySection />
      <DemoSection />
      <Footer/>
    </MainArea>
  );
}
